source "https://rubygems.org"

gem "byebug"
gem "cucumber"
gem "capybara"
gem "ffi"
gem "httparty"
gem "json" 
gem "poltergeist"
gem "rake"
gem "report_builder"
gem "rspec"
gem "selenium-webdriver"
gem "site_prism"